<?PHP
/**
 * index.php
 *
 * longdesc
 *
 * LICENSE: This source file is subject to version 4.0 of the Creative Commons
 * license that is available through the world-wide-web at the following URI:
 * https://creativecommons.org/licenses/by/4.0/
 *
 * @category   Geochronology
 * @package    Geochron Portal
 * @author     Jason Ash <jasonash@ku.edu>
 * @copyright  IEDA (http://www.iedadata.org/)
 * @license    https://creativecommons.org/licenses/by/4.0/  Creative Commons License 4.0
 * @version    GitHub: $
 * @link       http://www.geochron.org
 * @see        Geochron, Geochronology
 */

//exit();
//ini_set('session.cookie_path',			'/geochron2/');
ini_set('session.cookie_path',			'/');
session_start();

include("includes/geochron-frontpage-header.htm");

function getPic(){

	$images = array("monazite_X.jpg","zircon-X.jpg","SIMSChamber2.jpg","rutile_14.jpg","equipment1.jpg","rutile1.jpg","97080058-30FN.jpg","sims.jpg","21550-extline.jpg","equipment6.jpg","Figura-tema5A.jpg","monazites.jpg","monazite1.jpg","monazite2.jpg","tims.jpg");

	$image = $images[rand(0,count($images)-1)];

	return $image;

}



?>
<br><br><br>



<?$_SESSION['script']="index.php";?>



<div style="padding:0px;background-color:white;width:960px;margin:0 auto;">

	<table>
		<tr>
			<td valign="top">
				<div style="padding-right:10px;">
					<div align="center" style="border-bottom: 1px black solid;padding-bottom:15px;"><img src="/images/logo-320.jpg"/></div>
					<div style="padding-top:15px;"><img style="width:450px;" src="/images/<?=getPic();?>"/></div>
					<div class="aboutpage">
						<div align="center" style="padding-top:15px;">
							<div>Geochron is a project of <a href="http://earthchem.org/" target="_blank">EarthChem</a> and <a href="http://earth-time.org/" target="_blank">EARTHTIME</a></div>
							<div align="center">
								<a href="/aboutearthchem.php">About EarthChem</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/aboutearthtime.php">About EARTHTIME</a>
							</div>
						</div>
					</div>
				</div>
			</td>
			<td valign="top" style="border-left: 1px black solid;">
				<div style="padding-left:15px;">
					<div style="font-size:1.4em;font-weight:bold;color:#8a1e04;">What is Geochron?</div>
					<div style="line-height:15px;font-size:12px;">
					Geochron is a database system designed to capture complete 
					data and metadata to document geochronologic age estimation, 
					allowing future reuse, recalculation, and integration with 
					other data.<br><br>

					The goal is to capture this information at its source--the 
					data reduction programs used in labs to analyze and reduce 
					data coming directly from instrumentation. The human operators 
					of the equipment should not need to re-enter data that are 
					acquired or generated by computers in the first place.<br><br>

					Data can be ingested from a variety of data reduction 
					programs that are used widely in the various geochronology 
					and thermochronology communities. These programs have been 
					adapted to seamlessly upload standardized data to the Geochron 
					database with minimal input from the operator.<br><br>
					</div>

					<fieldset class="aboutpage" style="border: 1px solid #CDCDCD; padding: 8px; padding-bottom:0px; margin: 8px 0">
						<legend style="color:#8a1e04;"><strong>Geochron News</strong></legend>
							News items here...<br>
							News items here...<br>
							News items here...<br>
							News items here...<br>
							News items here...<br>
							News items here...<br>
							News items here...<br>
					</fieldset>
				</div>
			</td>
		</tr>
	</table>

</div>



<style type="text/css">
	.prop {
		height:50px;
		float:right;
		width:1px;
	}

	.clear {
		clear:both;
		height:1px;
		overflow:hidden;
	}
</style>




<?
include("includes/geochron-secondary-footer.htm");
?>